### PR TITLE
update license list to v3.10 (2020-08-03)

### PR DESCRIPTION
**Pull request by kemitchell**

### CODE REVIEW

**Comment by kemitchell** [comment]
@shinnn would you like to add me to this repo and the npm package? That was I can update without troubling you.

**Comment by kemitchell** [comment]
Alternatively, we could move this repo into the @jslicense org, and I can add you there.

**Comment by codemacabre** [comment]
@shinnn Is there anything we can do to help push this PR through or as @kemitchell suggests move the repo to the @jslicense org? I gather [quite a number of repos / packages](https://github.com/shinnn/spdx-license-ids/network/dependents?package_id=UGFja2FnZS0xNDQ2OTk1Mw%3D%3D) rely on this being kept up-to-date so it'd be good to ensure it's as active as possible.

**Comment by kemitchell** [comment]
@shinnn, with great respect, I will create a new successor package under the @jslicense organization, so that people can begin to use their new licenses without errors from this package falling behind. I will make sure to credit you in the README there. If you would like to maintain the package with me, I will also be happy to add you on GitHub and npm. I do not want to take any credit or recognition away from your long service here on spdx-license-ids.

Otherwise, I hope that you are alright and still feeling good about your contributions to licensing work around npm. If you would like to reach out to me privately, e-mail me anytime at kyle@kemitchell.com.

**Review by shinnn — APPROVED** [review]

**Comment by shinnn** [comment]
May I transfer this repo to @jslicense organization, @kemitchell?

**Comment by kemitchell** [comment]
@shinnn, I am so glad to hear from you! I hope that you are doing alright!

Please feel free to transfer this repository to the @jslicense organization. I believe you are already a member of that organization.

I would be glad to help you keep this package up to date from then on.

**Comment by kemitchell** [comment]
@shinnn, just checking in to see if you had trouble transferring to the @jslicense org. I will be happy to help. If you would like to add me (~kemitchell) as a publisher of the npm package, as well, I can handle publishing the 3.10 upgrade to the public registry.

I don't want to pester you. At the same time, a number of folks have reached out about being blocked. Before I heard from you, I did pull together a new package with a GitHub Action to automatically check for SPDX updates: https://github.com/jslicense/spdx-license-identifiers.json/actions

I will make a note to move forward with that package next Monday if I haven't heard from you. We can always revert to spdx-license-ids again, if that's what we want to do long-term.

**Pull request merged**
