### PR TITLE
Add LICENSE file

### PR DESCRIPTION
**Pull request by opichals**

### CODE REVIEW

**Comment by Eli-Black-Work** [comment]
Would love to see this get included :)

**Comment by shinnn** [comment]
As my understanding CC0-1.0 doesn't require license and copyright notice, isn't it?

**Comment by Eli-Black-Work** [comment]
Ah, you might be right, sorry :)

However, adding a LICENSE can still be helpful, because then programs that scan for LICENSE files may be able to more easily determine what type of license this project is licensed under :)

**Comment by shinnn** [comment]
Even if an npm package has no LICENSE file, programs still can detect its license by parsing `package.json` file.

https://github.com/shinnn/spdx-license-ids/blob/09f914ab6c75354b80c18d8343c5dbbd210adcb3/package.json#L7

Though I'm going to pass on this proposal, thanks for trying to contribute to this project, @opichals.

**Pull request closed without merging**
