### PR TITLE
update license list to v3.8 (2020-02-09)

### PR DESCRIPTION
**Pull request by kemitchell**
See https://github.com/spdx/license-list-XML/releases/tag/v3.8

### CODE REVIEW

**Review by roryokane — APPROVED** [review]
I manually compared these 13 added licenses to the [license-list-XML release notes](https://github.com/spdx/license-list-XML/releases) for version 3.7 and 3.8 and confirm that they include all the added licenses. This PR’s additions don’t include two licenses/exceptions mentioned in those release notes, “GPL-3.0-linking-exception” and “GPL-3.0-linking-source-exception”, but those are exceptions, not licenses, so that’s fine.

If you were waiting for a third party’s approval, you have it. I think you can merge this and make a new release of `spdx-license-ids`.

(If you’re wondering how I found this PR and why I would care, I found this repo while trying to fix Yarn v1.22.4’s warning “License should be a valid SPDX license expression” for a license that was added in `spdx-license-ids` v3.0.5. I made local changes identical to yours before I noticed you already had a PR for it. I don’t personally care about any of the licenses in this PR, so no rush.)

**Comment by kemitchell** [comment]
@roryokane thanks for this comment. I'm updating `spdx-exceptions` now.

**Comment by kemitchell** [comment]
@shinnn spdx-exceptions@2.3.0 has the latest v3.8 SPDX data.

**Comment by kemitchell** [comment]
Superseded by #19.

**Pull request closed without merging**
