### PR TITLE
rebuild files for SPDX 3.0 release

### PR DESCRIPTION
**Pull request by kemitchell**
I reran the build script to catch updates in version 3.0 of the SPDX license list.

Two thoughts:

1.  We should think about versioning.  Perhaps bump to 3.0.0, to track the license list?

2.  We should consider extending the API to do something about deprecated license identifiers.  In particular, `GPL-2.0` and similar have been deprecated in favor of `GPL-2.0-only` and `GPL-2.0-or-later`.  Same for AGPL and LGPL.

### CODE REVIEW

**Comment by kemitchell** [comment]
Related: https://github.com/npm/npm/issues/19558

**Comment by kemitchell** [comment]
It looks like `get-spdx-license-ids` already handles deprecated license data. It's just that spdx.org isn't correctly reporting which licenses are deprecated.

https://github.com/spdx/tools/issues/144
https://github.com/shinnn/get-spdx-license-ids/issues/4

**Comment by shinnn** [comment]
> bump to 3.0.0

Yes, it's reasonable as this seems to be a breaking change.

> We should consider extending the API to do something about deprecated license identifiers.

I prefer,

1. Exclude every deprecated license from this module.
2. Create another module `deprecated-spdx-license-ids` that only includes . If a user needs a list of  the all, both deprecated and non-deprecated licenses, they can `require` both modules:

```js
const licenseIds = require('spdx-license-ids');
const deprecatedLicenseIds = require('deprecated-spdx-license-ids');
const allLicenseIds = [...licenseIds, ...deprecatedLicenseIds];
```

However, I assume the main consumer of this module is npm CLI, so I'll follow its needs.

**Comment by kemitchell** [comment]
@shinn, thanks! If you prefer to split the package in two, one for deprecated and one for not-deprecated, go for it. I'd appreciate you mentioning me, so I can do what needs doing for npm.

**Comment by shinnn** [comment]
@kemitchell Finally I decided,

* For maintainability, instead of publishing two packages, I'll create a new file `deprecated.json` to *this* repository.
* As stated in https://github.com/shinnn/spdx-license-ids/pull/8#issuecomment-356492194, I'll update `index.js` to include non-deprecated IDs only.

The final API is the following:

```javascript
// non-deprecated IDs
const licenseIds = require('spdx-license-ids');

// deprecated IDs
const deprecatedLicenseIds = require('spdx-license-ids/deprecated');

// all IDs
const allLicenseIds = [...licenseIds, ...deprecatedLicenseIds];
```

**Review by shinnn — APPROVED** [review]
For now, publishing this as a prerelease version.

**Comment by kemitchell** [comment]
That API works fine for me. Whatever works best for you is fine.

**Comment by shinnn** [comment]
[🚀 3.0.0](https://github.com/shinnn/spdx-license-ids/releases/tag/v3.0.0)

**Pull request merged**
