### PR TITLE
Update License List to v3.21, remove checking for ids end with +

### PR DESCRIPTION
**Pull request by cbsMartin**
- All licenses that ends with + now are deprecated. 
- Update License List to v3.21

### CODE REVIEW

**Comment by kemitchell** [comment]
Are these licenses not marked deprecated in SPDX's JSON?

**Comment by cbsMartin** [comment]
> Are these licenses not marked deprecated in SPDX's JSON?

From the official document with all SPDX license they are marked as deprecated but in current logic they are skipped.

**Comment by kemitchell** [comment]
Oh, boy.

SPDX has done something drastic with their license IDs, and I've yet to read my way up on it. If `+` is now a valid identifier character, we are going to have fun times in the expression parser, too.

**Comment by kemitchell** [comment]
I've reached out to SPDX for clarification.

I suspect, but do not yet know, that they added some license _expressions_ to the license _list_, just for the purpose of deprecating them. That's expressing the idea that they would rather see "GPL-2.0-or-later" than "GPL-2.0+", but _not_ that "GPL-2.0" itself is a valid license ID, such that "GPL-2.0++" would be a valid license _expression_.

We'll see.

**Comment by kemitchell** [comment]
I've gone ahead and matched v3.21 of the SPDX list in spdx-license-ids@3.0.14. Will wait for response from them to decide what to do about filtering or not filtering IDs ending in `+`.

**Comment by kemitchell** [comment]
Gary O'Neall from SPDX confirms there are in fact IDs that end in "+", and they are all deprecated now. I've cherry-picked your bf86ce28b8f222e05d64b177498ca364a89ad114 and pushed to `main`.

**Pull request closed without merging**
