### PR TITLE
update license list to v3.6 (2019-07-10)

### PR DESCRIPTION
**Pull request by kemitchell**
https://github.com/spdx/license-list-data/releases/tag/v3.6

### CODE REVIEW

**Review by shinnn — APPROVED** [review]

**Comment by shinnn** [comment]
@kemitchell Thanks for your continuous contribution on this project. I’ve invited you to [the npm package](https://www.npmjs.com/package/spdx-license-ids) and this repository as a maintainer. I should have done it earlier.

**Comment by shinnn** [comment]
Published as [`3.0.5`](https://github.com/shinnn/spdx-license-ids/commit/2bc004aae6f30d625d3aad95eac09d9aaf1c97cc).

**Comment by kemitchell** [comment]
@shinnn, thank you!

I have accepted the invitation to this repo, but haven't seen any message about the npm package yet.

I have also invited _you_ to github.com/jslicense, the home for a number of important packages and tools related to licensing.

**Comment by shinnn** [comment]
I actually invited you to the package maintainers by using the web interface of npmjs.com,



but interestingly the npm CLI says,

```
$ npm owner ls spdx-license-ids
shinnn <snnskwtnb@gmail.com>
```

I guess npm server takes some time for invitation.

**Pull request merged**
